ARG version
FROM almalinux:${version}
# ENV course="Devops with AWS" \
#     duration="120 hrs"
ARG course="Devops with AWS" \
    duration="120 hrs"
RUN echo "Course: $course, Duration:$duration"
CMD ["sleep","100"]